#!/usr/bin/env python3
"""
Downloads 1°×1° SRTMGL1 GeoTIFF tiles from OpenTopography.
Reads tile URLs from dem.csv (generated by fetch_dem_urls.py).

Run from inside the geotiffs/ directory:
    ./download.sh

Skips tiles that have already been downloaded (safe to re-run).
Uses 4 parallel workers to speed things up.
"""

import csv
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests

SCRIPT_DIR = Path(__file__).parent
GEOTIFFS_DIR = SCRIPT_DIR / "geotiffs"
DEM_CSV = GEOTIFFS_DIR / "dem.csv"
MAX_WORKERS = 4
RETRY_ATTEMPTS = 3
RETRY_DELAY = 5  # seconds between retries


def download_tile(tile_id: str, url: str) -> str:
    """Download a single tile, retrying on failure. Returns a status message."""
    filename = GEOTIFFS_DIR / f"USGS_1_{tile_id}.tif"

    if filename.exists() and filename.stat().st_size > 0:
        return f"  skip  {filename.name} (already exists)"

    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            response = requests.get(url, stream=True, timeout=120)
            response.raise_for_status()

            # Check we got a GeoTIFF and not an error message
            content_type = response.headers.get("Content-Type", "")
            if "json" in content_type or "text" in content_type:
                body = response.text[:200]
                raise ValueError(f"Expected GeoTIFF but got {content_type}: {body}")

            with open(filename, "wb") as f:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    f.write(chunk)

            size_mb = filename.stat().st_size / 1_000_000
            return f"  done  {filename.name} ({size_mb:.1f} MB)"

        except Exception as e:
            if attempt < RETRY_ATTEMPTS:
                time.sleep(RETRY_DELAY)
            else:
                if filename.exists():
                    filename.unlink()
                return f"  FAIL  {tile_id}: {e}"

    return f"  FAIL  {tile_id}: unknown error"


def main() -> None:
    if not DEM_CSV.exists():
        print(f"Error: {DEM_CSV} not found. Run fetch_dem_urls.py first.", file=sys.stderr)
        sys.exit(1)

    tiles: list[tuple[str, str]] = []
    with open(DEM_CSV, newline="") as f:
        for row in csv.DictReader(f):
            tiles.append((row["tile_id"], row["url"]))

    if not tiles:
        print("No tiles found in dem.csv.", file=sys.stderr)
        sys.exit(1)

    print(f"Downloading {len(tiles)} tiles ({MAX_WORKERS} parallel workers) ...")

    failed = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(download_tile, tid, url): tid for tid, url in tiles}
        for future in as_completed(futures):
            msg = future.result()
            print(msg)
            if msg.strip().startswith("FAIL"):
                failed.append(futures[future])

    print()
    if failed:
        print(f"WARNING: {len(failed)} tile(s) failed: {', '.join(failed)}", file=sys.stderr)
        sys.exit(1)
    else:
        print(f"All {len(tiles)} tiles downloaded successfully.")


if __name__ == "__main__":
    main()
