#!/usr/bin/env python3
"""
Preprocesses elevation and border data for ridge_map.py.

Usage:
    ./preprocess.py --state California
    ./preprocess.py --state Colorado

Outputs:
    state_dem.py          — constants module imported by ridge_map.py
    state_border_lon.npy  — border longitude array
    state_border_lat.npy  — border latitude array
"""

import argparse
from os import listdir
import re

import numpy as np
import rasterio

from utils import fetch_state_border

TIF_DIR = "./geotiffs"
LAT_LON_RE = re.compile(r".*([ns]\d{1,2})([ew]\d{1,3}).*")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Preprocess DEM data for a US state.")
    parser.add_argument(
        "--state", default="California",
        help='State name as it appears in Census data, e.g. "Colorado" (default: California)'
    )
    args = parser.parse_args()
    state_name = args.state

    # --- Border ---
    lon, lat = fetch_state_border(state_name)
    np.save("state_border_lon.npy", lon)
    np.save("state_border_lat.npy", lat)
    print(f"Saved {state_name} border: {len(lon)} vertices")

    # --- Elevation tiles ---
    elev_max = -1_000_000
    elev_min =  1_000_000
    lon_max  = -1_000_000
    lon_min  =  1_000_000
    lat_max  = -1_000_000
    lat_min  =  1_000_000

    frames_lon_min =  1000
    frames_lon_max = -1000
    frames_lat_min =  1000
    frames_lat_max = -1000

    frame_width: int | None = None
    frame_height: int | None = None

    tifs = [f for f in sorted(listdir(TIF_DIR)) if re.search(r"\.tif$", f, re.IGNORECASE)]
    if not tifs:
        raise FileNotFoundError(
            f"No .tif files found in {TIF_DIR}/. "
            "Run download.py first."
        )

    for f in tifs:
        path = f"{TIF_DIR}/{f}"
        print(path)
        dataset = rasterio.open(path)
        m = LAT_LON_RE.match(dataset.name)
        if not m:
            print(f"  WARNING: could not parse lat/lon from filename, skipping {f}")
            dataset.close()
            continue

        frame_lon = int(m.group(2).replace("w", "-").replace("e", ""))
        frames_lon_min = min(frames_lon_min, frame_lon)
        frames_lon_max = max(frames_lon_max, frame_lon)
        frame_lat = int(m.group(1).replace("s", "-").replace("n", ""))
        frames_lat_min = min(frames_lat_min, frame_lat)
        frames_lat_max = max(frames_lat_max, frame_lat)

        frame_width  = dataset.width
        frame_height = dataset.height
        print(f"  bounds: {dataset.bounds}  size: {frame_width}x{frame_height}")

        band = dataset.read(1).astype(float)
        band[band == -999999] = np.nan

        elev_max = max(elev_max, float(np.nanmax(band)))
        elev_min = min(elev_min, float(np.nanmin(band)))
        lon_max  = max(lon_max,  dataset.bounds.right)
        lon_min  = min(lon_min,  dataset.bounds.left)
        lat_max  = max(lat_max,  dataset.bounds.top)
        lat_min  = min(lat_min,  dataset.bounds.bottom)
        dataset.close()

    if frame_width is None:
        raise RuntimeError("No valid GeoTIFF tiles were processed.")

    with open("state_dem.py", "w") as f:
        f.write(f'# Auto-generated by preprocess.py for: {state_name}\n')
        f.write('import numpy as np\n\n')
        f.write(f'STATE_NAME     = "{state_name}"\n')
        f.write(f'ELEV_MAX       = {elev_max}\n')
        f.write(f'ELEV_MIN       = {elev_min}\n')
        f.write(f'LON_MAX        = {lon_max}\n')
        f.write(f'LON_MIN        = {lon_min}\n')
        f.write(f'LAT_MAX        = {lat_max}\n')
        f.write(f'LAT_MIN        = {lat_min}\n')
        f.write('STATE_BORDER_LON = np.load("state_border_lon.npy")\n')
        f.write('STATE_BORDER_LAT = np.load("state_border_lat.npy")\n')
        f.write(f'FRAME_WIDTH    = {frame_width}\n')
        f.write(f'FRAME_HEIGHT   = {frame_height}\n')
        f.write(f'FRAMES_LON_MIN = {frames_lon_min}\n')
        f.write(f'FRAMES_LON_MAX = {frames_lon_max}\n')
        f.write(f'FRAMES_LAT_MIN = {frames_lat_min}\n')
        f.write(f'FRAMES_LAT_MAX = {frames_lat_max}\n')
    print(f"Wrote state_dem.py for {state_name}")
